.github/workflows/mirror.yml

Mirror of [meta-selinux](https://git.yoctoproject.org/cgit/cgit.cgi/meta-selinux/).
closes #1

Mirror of yocto/meta-selinux

---

.github/workflows/mirror.yml
README.md

Updates the mirrors once a day. The time (11 UTC) was chosen by random, no real reason.
Readme badges added.
closes #2

Daily cron

---

.github/workflows/mirror.yml

Enable `StrictHostKeyChecking`. It's only supported via fork at the moment.
closes #4

Enable StrictHostKeyChecking

---

.github/workflows/mirror.yml

Changes have been merged upstream (#4, #8).

Reset action branch

---

.github/workflows/mirror.yml

Add meta-openembedded to mirror list (#12)

---

README.md

Warning added to docs

---

.github/workflows/mirror.yml

Add vsphere-automation-sdk-python mirror. Destination repo is a fork.
closes #35

vsphere-automation-sdk-python mirror

---

.github/workflows/mirror.yml

Mirror of a VSCode plugin used for graphical debugging.

Add graphical-debugging-vscode mirror

---

.github/workflows/mirror.yml

Mirror SciTEQt project instead of keeping a fork.

Add SciTEQt to mirror list

---

.github/workflows/mirror.yml

Add funq mirror

---

.github/workflows/mirror.yml

Mirror of *opcua-asyncio*.
closes #46

Mirror opcua-asyncio

---

.github/workflows/mirror.yml

Syncs the fork of the Mingw Packages repo. It wasn't updated on a regular basis, but manually only.

Sync mingw packages repo

---

.github/workflows/mirror.yml

Add NetworkManager and network-manager-applet to list of mirrors.
Keys are already deployed to related repos.

Add NetworkManager and network-manager-applet

---

.github/workflows/mirror.yml

Provide mirror of meta-conan

---

.github/workflows/mirror.yml

Add mirrors for meta-freescale and meta-freescale-distro.
closes #57

Add freescale mirrors

---

.github/workflows/mirror.yml

Mirror of `meta-security`.
closes #68

Mirror meta-security

---

.github/workflows/mirror.yml

Mirror configuration for yocto-kernel-cache and linux-yocto (#75).

Add mirror for yocto-kernel-cache and linux-yocto (#75)

---

.github/workflows/mirror.yml

Next try for #75.
The repo has been synced manually now.

Re-enable mirror of linux-yocto

---

.github/workflows/mirror.yml

Mirror openssh-portable for downstream consumption

Add openssh-portable to mirrors (#74)

---

.github/workflows/mirror.yml

Mirror rustsec/advisory-db 

---

.github/workflows/mirror.yml

Adapt src_repo for yocto-meta-kf6

---

.github/workflows/mirror.yml

add yocto-vex-check (#110)
